// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://duvmlsjbdstvnroastxy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1dm1sc2piZHN0dm5yb2FzdHh5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyODk5MzgsImV4cCI6MjA2OTg2NTkzOH0.Lq-9yJfRvfHP5a11J8p08EaAf0mk7gQuo8VRWhT3868";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});